package com.firebase.loginauth

import java.text.SimpleDateFormat
import java.util.*

/**
 * Data class representing an automated business report
 */
data class AutomatedReport(
    val id: String = UUID.randomUUID().toString(),
    val reportType: ReportType = ReportType.DAILY,
    val reportDate: String = getCurrentDateBengali(),
    val generatedAt: Long = System.currentTimeMillis(),
    val reportPeriod: ReportPeriod = ReportPeriod(),
    val salesSummary: SalesSummary = SalesSummary(),
    val orderSummary: OrderSummary = OrderSummary(),
    val customerSummary: CustomerSummary = CustomerSummary(),
    val inventorySummary: InventorySummary = InventorySummary(),
    val expenseSummary: ExpenseSummary = ExpenseSummary(),
    val financialSummary: FinancialSummary = FinancialSummary(),
    val topPerformers: TopPerformers = TopPerformers(),
    val insights: List<BusinessInsight> = emptyList(),
    val recommendations: List<String> = emptyList(),
    val isAutoGenerated: Boolean = true,
    val status: ReportStatus = ReportStatus.GENERATED
)

/**
 * Enum for report types
 */
enum class ReportType(val displayNameBn: String, val displayNameEn: String) {
    DAILY("দৈনিক", "Daily"),
    WEEKLY("সাপ্তাহিক", "Weekly"),
    MONTHLY("মাসিক", "Monthly"),
    QUARTERLY("ত্রৈমাসিক", "Quarterly"),
    YEARLY("বার্ষিক", "Yearly"),
    CUSTOM("কাস্টম", "Custom")
}

/**
 * Enum for report status
 */
enum class ReportStatus(val displayNameBn: String, val displayNameEn: String) {
    GENERATING("তৈরি হচ্ছে", "Generating"),
    GENERATED("তৈরি", "Generated"),
    SENT("পাঠানো", "Sent"),
    FAILED("ব্যর্থ", "Failed")
}

/**
 * Data class for report period
 */
data class ReportPeriod(
    val startDate: String = "",
    val endDate: String = "",
    val periodDescription: String = ""
)

/**
 * Data class for sales summary in reports
 */
data class SalesSummary(
    val totalSales: Double = 0.0,
    val totalOrders: Int = 0,
    val averageOrderValue: Double = 0.0,
    val salesByPaymentMethod: Map<String, Double> = emptyMap(),
    val salesByCustomerType: Map<String, Double> = emptyMap(),
    val salesGrowth: Double = 0.0,
    val salesTrend: SalesTrend = SalesTrend.STABLE
)

/**
 * Data class for order summary in reports
 */
data class OrderSummary(
    val totalOrders: Int = 0,
    val completedOrders: Int = 0,
    val pendingOrders: Int = 0,
    val cancelledOrders: Int = 0,
    val ordersByStatus: Map<String, Int> = emptyMap(),
    val ordersByPriority: Map<String, Int> = emptyMap(),
    val averageOrderProcessingTime: Double = 0.0,
    val orderCompletionRate: Double = 0.0
)

/**
 * Data class for customer summary in reports
 */
data class CustomerSummary(
    val totalCustomers: Int = 0,
    val newCustomers: Int = 0,
    val activeCustomers: Int = 0,
    val customersByType: Map<String, Int> = emptyMap(),
    val customerRetentionRate: Double = 0.0,
    val averageCustomerValue: Double = 0.0,
    val topCustomersByRevenue: List<CustomerRevenue> = emptyList()
)

/**
 * Data class for inventory summary in reports
 */
data class InventorySummary(
    val totalStock: Int = 0,
    val stockByType: Map<String, Int> = emptyMap(),
    val lowStockItems: List<String> = emptyList(),
    val stockTurnoverRate: Double = 0.0,
    val stockValue: Double = 0.0,
    val stockMovement: Map<String, Int> = emptyMap()
)

/**
 * Data class for expense summary in reports
 */
data class ExpenseSummary(
    val totalExpenses: Double = 0.0,
    val expensesByCategory: Map<String, Double> = emptyMap(),
    val expensesByDate: Map<String, Double> = emptyMap(),
    val averageDailyExpense: Double = 0.0,
    val expenseGrowth: Double = 0.0,
    val largestExpense: Double = 0.0,
    val expenseCount: Int = 0
)

/**
 * Data class for financial summary in reports
 */
data class FinancialSummary(
    val totalRevenue: Double = 0.0,
    val totalExpenses: Double = 0.0,
    val netProfit: Double = 0.0,
    val profitMargin: Double = 0.0,
    val cashFlow: Double = 0.0,
    val outstandingPayments: Double = 0.0,
    val expensesByCategory: Map<String, Double> = emptyMap(),
    val revenueGrowth: Double = 0.0
)

/**
 * Data class for top performers in reports
 */
data class TopPerformers(
    val topCustomers: List<CustomerRevenue> = emptyList(),
    val topProducts: List<ProductSales> = emptyList(),
    val topSalesAreas: List<AreaSales> = emptyList(),
    val bestPerformingDays: List<DayPerformance> = emptyList()
)

/**
 * Data class for customer revenue
 */
data class CustomerRevenue(
    val customerId: String = "",
    val customerName: String = "",
    val totalRevenue: Double = 0.0,
    val orderCount: Int = 0,
    val averageOrderValue: Double = 0.0
)

/**
 * Data class for product sales
 */
data class ProductSales(
    val productType: String = "",
    val quantitySold: Int = 0,
    val revenue: Double = 0.0,
    val profitMargin: Double = 0.0
)

/**
 * Data class for area sales
 */
data class AreaSales(
    val area: String = "",
    val totalSales: Double = 0.0,
    val orderCount: Int = 0,
    val customerCount: Int = 0
)

/**
 * Data class for day performance
 */
data class DayPerformance(
    val date: String = "",
    val sales: Double = 0.0,
    val orders: Int = 0,
    val profit: Double = 0.0
)

/**
 * Data class for business insights
 */
data class BusinessInsight(
    val id: String = UUID.randomUUID().toString(),
    val type: InsightType = InsightType.SALES,
    val title: String = "",
    val description: String = "",
    val impact: InsightImpact = InsightImpact.MEDIUM,
    val actionRequired: Boolean = false,
    val recommendation: String = ""
)

/**
 * Enum for insight types
 */
enum class InsightType(val displayNameBn: String, val displayNameEn: String) {
    SALES("বিক্রয়", "Sales"),
    INVENTORY("ইনভেন্টরি", "Inventory"),
    CUSTOMER("গ্রাহক", "Customer"),
    FINANCIAL("আর্থিক", "Financial"),
    OPERATIONAL("পরিচালনা", "Operational")
}

/**
 * Enum for insight impact
 */
enum class InsightImpact(val displayNameBn: String, val displayNameEn: String) {
    LOW("কম", "Low"),
    MEDIUM("মধ্যম", "Medium"),
    HIGH("উচ্চ", "High"),
    CRITICAL("গুরুত্বপূর্ণ", "Critical")
}

/**
 * Enum for sales trend
 */
enum class SalesTrend(val displayNameBn: String, val displayNameEn: String) {
    INCREASING("বৃদ্ধি", "Increasing"),
    DECREASING("হ্রাস", "Decreasing"),
    STABLE("স্থিতিশীল", "Stable"),
    VOLATILE("অস্থির", "Volatile")
}

/**
 * Data class for report configuration
 */
data class ReportConfig(
    val id: String = UUID.randomUUID().toString(),
    val reportType: ReportType = ReportType.DAILY,
    val isEnabled: Boolean = true,
    val autoGenerate: Boolean = true,
    val generateTime: String = "09:00", // 24-hour format
    val recipients: List<String> = emptyList(),
    val includeCharts: Boolean = true,
    val includeInsights: Boolean = true,
    val includeRecommendations: Boolean = true,
    val customFilters: Map<String, String> = emptyMap(),
    val lastGenerated: Long = 0L,
    val nextGeneration: Long = 0L
)

/**
 * Utility function to get current date in Bengali format
 */
private fun getCurrentDateBengali(): String {
    val sdf = SimpleDateFormat("dd MMMM yyyy", Locale("bn", "BD"))
    return sdf.format(Date())
}

/**
 * Utility function to get date range for report type
 */
fun getDateRangeForReportType(reportType: ReportType): ReportPeriod {
    val calendar = Calendar.getInstance()
    val endDate = calendar.time
    
    when (reportType) {
        ReportType.DAILY -> {
            calendar.add(Calendar.DAY_OF_MONTH, -1)
            val startDate = calendar.time
            return ReportPeriod(
                startDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(startDate),
                endDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(endDate),
                periodDescription = "গতকাল"
            )
        }
        ReportType.WEEKLY -> {
            calendar.add(Calendar.WEEK_OF_YEAR, -1)
            val startDate = calendar.time
            return ReportPeriod(
                startDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(startDate),
                endDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(endDate),
                periodDescription = "গত সপ্তাহ"
            )
        }
        ReportType.MONTHLY -> {
            calendar.add(Calendar.MONTH, -1)
            val startDate = calendar.time
            return ReportPeriod(
                startDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(startDate),
                endDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(endDate),
                periodDescription = "গত মাস"
            )
        }
        ReportType.QUARTERLY -> {
            calendar.add(Calendar.MONTH, -3)
            val startDate = calendar.time
            return ReportPeriod(
                startDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(startDate),
                endDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(endDate),
                periodDescription = "গত ত্রৈমাসিক"
            )
        }
        ReportType.YEARLY -> {
            calendar.add(Calendar.YEAR, -1)
            val startDate = calendar.time
            return ReportPeriod(
                startDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(startDate),
                endDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(endDate),
                periodDescription = "গত বছর"
            )
        }
        ReportType.CUSTOM -> {
            return ReportPeriod(
                startDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(endDate),
                endDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(endDate),
                periodDescription = "কাস্টম"
            )
        }
    }
}
